'use client';

import { useEffect, useState } from 'react';
import { AppShell } from '../../components/shells';
import { Alert, Button, Card, PageHeader, Skeleton } from '../../components/ui';

type SubscriptionPlan = { tier: string; title: string; description: string; rank_boost: number; analytics: boolean; };
type FeaturedOption = { type: string; title: string; description: string; suggested_amount_cents: number; duration_days: number; };

export default function BillingPage() {
  const [planData, setPlanData] = useState<any>(null); const [featuredOptions, setFeaturedOptions] = useState<FeaturedOption[]>([]); const [selectedTier, setSelectedTier] = useState('free'); const [selectedFeatured, setSelectedFeatured] = useState('boost'); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  useEffect(() => { Promise.all([fetch('/api/revenue/subscriptions'), fetch('/api/revenue/featured')]).then(async ([subscription, listing]) => { const subscriptionData = await subscription.json(); const listingData = await listing.json(); if (!subscription.ok) throw new Error(subscriptionData.error ?? 'Could not load billing.'); setPlanData(subscriptionData.subscription ?? subscriptionData); setFeaturedOptions(listingData.options ?? []); setSelectedTier(subscriptionData.subscription?.current_tier ?? 'free'); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Could not load billing.')); }, []);
  async function upgradePlan() { setError(''); setStatus('Updating plan…'); try { const amount = selectedTier === 'pro' ? 12000 : selectedTier === 'elite' ? 24000 : 0; const response = await fetch('/api/revenue/subscriptions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ subscription_tier: selectedTier, amount_cents: amount, currency: 'NGN' }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to update plan.'); setPlanData({ ...planData, current_tier: selectedTier }); setStatus(`Updated to ${selectedTier}.`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update plan.'); setStatus(''); } }
  async function buyFeatured() { setError(''); setStatus('Purchasing featured listing…'); try { const option = featuredOptions.find((item) => item.type === selectedFeatured); if (!option) throw new Error('Featured option not found.'); const response = await fetch('/api/revenue/featured', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: option.type, duration_days: option.duration_days, amount_cents: option.suggested_amount_cents, currency: 'NGN' }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to purchase featured listing.'); setStatus('Featured listing purchased successfully.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to purchase listing.'); setStatus(''); } }
  return <AppShell persona="provider"><PageHeader eyebrow="Provider finance" title="Billing and growth" description="Manage your Kajola plan and optional listing promotion." />{error ? <Alert tone="error">{error}</Alert> : null}{status ? <Alert tone="success">{status}</Alert> : null}{!planData ? <Skeleton /> : <div className="kj-stack"><Card><p className="kj-page-header__eyebrow">Current plan</p><h2 className="kj-heading-2" style={{ textTransform: 'capitalize' }}>{planData.current_tier}</h2><p className="kj-muted">Platform fee: {planData.platform_fee_percent}% of paid bookings</p></Card><Card><h2 className="kj-heading-3">Subscription plans</h2><div className="kj-form" style={{ marginTop: 'var(--space-4)' }}>{planData.plans.map((plan: SubscriptionPlan) => <label className="kj-card" key={plan.tier}><input type="radio" name="plan" value={plan.tier} checked={selectedTier === plan.tier} onChange={() => setSelectedTier(plan.tier)} /> <strong>{plan.title}</strong><span className="kj-small kj-muted"> — {plan.description}</span></label>)}<Button onClick={upgradePlan}>Update plan</Button></div></Card><Card><h2 className="kj-heading-3">Featured listings</h2><div className="kj-form" style={{ marginTop: 'var(--space-4)' }}>{featuredOptions.map((option) => <label className="kj-card" key={option.type}><input type="radio" name="featured" value={option.type} checked={selectedFeatured === option.type} onChange={() => setSelectedFeatured(option.type)} /> <strong>{option.title}</strong><span className="kj-small kj-muted"> — {option.description} · ₦{(option.suggested_amount_cents / 100).toLocaleString()}</span></label>)}<Button onClick={buyFeatured} variant="secondary">Buy featured listing</Button></div></Card></div>}</AppShell>;
}
