export const INFO_PAGES = {
  about: { title: 'About Kajola', eyebrow: 'Company', summary: 'Kajola is building service-commerce infrastructure for customers and independent businesses across Africa.', sections: [['What we do', 'Customers discover providers, compare services, choose real availability, and manage appointments. Businesses organize services, bookings, customers, payments, and growth.'], ['Our principle', 'Local trust should be supported by clear information, reliable workflows, and tools designed for the realities of African markets.']] },
  blog: { title: 'Kajola stories', eyebrow: 'Blog', summary: 'Product notes and practical service-business guidance will be published here.', sections: [['Coming thoughtfully', 'The Kajola blog is being prepared. We will only publish articles when there is useful, reviewed material to share.']] },
  faq: { title: 'Frequently asked questions', eyebrow: 'Help', summary: 'Straight answers about finding providers and using Kajola.', sections: [['Is a booking confirmed immediately?', 'No. Kajola shows the real booking state. A reservation becomes confirmed only after the required booking and payment steps succeed.'], ['Can any service business join?', 'Kajola supports a broad service taxonomy and an Other option, so a business is not blocked because its type is new or specialized.']] },
  contact: { title: 'Contact Kajola', eyebrow: 'Support', summary: 'Need help with a booking, business profile, or Kajola account?', sections: [['Customer and business support', 'Use the support controls in your Kajola workspace. Public support channels will be listed here when they are operational.']] },
  privacy: { title: 'Privacy Policy', eyebrow: 'Legal & Trust', summary: 'Kajola is preparing its production privacy policy before public launch.', sections: [['Product-stage notice', 'This page is not a substitute for the final reviewed policy. Do not submit sensitive personal information outside Kajola’s designated account and booking flows.']] },
  terms: { title: 'Terms of Service', eyebrow: 'Legal & Trust', summary: 'Kajola is preparing its production terms before public launch.', sections: [['Product-stage notice', 'Final commercial terms, cancellation rules, and market-specific obligations will be published after legal review and before production use.']] },
  trust: { title: 'Kajola Trust Center', eyebrow: 'Legal & Trust', summary: 'Trust is built through clear provider information, verified actions, and honest booking states.', sections: [['Marketplace trust', 'Profiles may show verification, ratings, completed work, published services, prices, and availability where those records exist.'], ['Honest states', 'Kajola does not present a booking or payment as successful until the corresponding workflow confirms it.']] },
  security: { title: 'Security at Kajola', eyebrow: 'Legal & Trust', summary: 'Kajola separates customer, provider, owner, and operator access and protects server credentials from client code.', sections: [['Responsible access', 'Workspace and tenant authorization is enforced at API boundaries. Security concerns should be reported through the official contact channel when it becomes available.']] },
  business: { title: 'Kajola for Business', eyebrow: 'For businesses', summary: 'Turn your skill into a structured, discoverable, repeatable business.', sections: [['Operate in one place', 'Publish services, organize availability, receive bookings, serve customers, and understand performance from one Kajola workspace.']] },
  'business-resources': { title: 'Business resources', eyebrow: 'For businesses', summary: 'Practical resources for setting up and growing a service business on Kajola.', sections: [['Resources in development', 'Guides will appear here as onboarding, payments, and marketplace operations become available by market.']] },
  careers: { title: 'Careers at Kajola', eyebrow: 'Company', summary: 'Kajola is not listing open roles on this site today.', sections: [['Future opportunities', 'Verified openings and application instructions will be published here when roles are available.']] },
  partners: { title: 'Partner with Kajola', eyebrow: 'Company', summary: 'Kajola works toward dependable service commerce across payments, communications, trust, and local operations.', sections: [['Partnership information', 'A formal partner program is not yet open. Program details and official contact routes will appear here when available.']] },
} as const;

export type InfoPageSlug = keyof typeof INFO_PAGES;
