-- SUPERSEDED: This migration originally tried to CREATE types and tables that
-- migration 20260424000000_init_schema.sql already defines (booking_status,
-- payment_status, tenants, users, services, availability_windows, bookings).
-- Running it on a fresh db reset would fail with "type already exists" errors.
--
-- All SORF additions are applied additively in:
--   20260726000002_sorf_mvp_convergence.sql
--
-- This file is kept as a no-op to preserve the migration sequence on
-- any Supabase instances that have already recorded it in the history table.
SELECT 1; -- no-op
